Repository epsagon/epsagon-browser, pull requests merged in 2021-08, with the labels that each got.

#18 rename web2nodejs, react2web
  README.md
  packages/react/README.md
  packages/react/package-lock.json
  packages/react/package.json
  packages/react/src/instrumentation/redirectInstrumentation.js
  packages/react/src/web-tracer.js
  packages/web/README.md
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/M

#20 fix(web): revert epsagon typo
  README.md
  packages/react/README.md
  packages/react/package-lock.json
  packages/react/package.json
  packages/react/src/instrumentation/redirectInstrumentation.js
  packages/react/src/web-tracer.js
  packages/web/README.md
  packages/web/package-lock.json
  packages/web/package.json
Labels: size/M

#21 Bug/epsagon web/sdk 107
  README.md
  packages/web/README.md
Labels: size/XS

#22 Bug/epsagon web/sdk 107
  packages/web/src/index.js
Labels: size/XS

#23 fix(readme): release version
  README.md
Labels: size/XS

#25 Update README.md
  packages/web/README.md
Labels: size/XS

#28 Update README.md
  README.md
Labels: size/XS

#33 fix(readme): release version
  README.md
Labels: size/XS

#34 Now using logger instead of console.log
  packages/web/README.md
  packages/web/src/exporter.js
  packages/web/src/instrumentation/fetchInstrumentation.js
  packages/web/src/web-tracer.js
  packages/web/test/helper.js
  packages/web/test/web-tracer.test.js
  packages/web/tsconfig.json
Labels: size/L

#35 docs: Change react import to react to web
  README.md
Labels: size/XS

#36 Update README.md
  README.md
Labels: size/XS

#37 fix(release-logger): release logger version
  packages/web/src/web-tracer.js
Labels: size/XS

#24 fix(error stacktrace): add stacktrace data to errors
  packages/web/src/exporter.js
  packages/web/src/instrumentation/documentLoadInstrumentation.js
  packages/web/src/instrumentation/fetchInstrumentation.js
Labels: size/M

#38 Feature/traceback/sdk 106
  packages/web/src/exporter.js
Labels: size/S

#40 docs(logger) updated main readme with logger config
  README.md
Labels: size/XS

#41 fix(empty-stack-bug): fix error empty stack issue
  packages/web/src/instrumentation/documentLoadInstrumentation.js
  packages/web/src/utils.js
  packages/web/test/docLoad.test.js
  packages/web/test/helper.js
Labels: size/M

#39 add configuration urlPatternsToIgnore
  packages/web/README.md
  packages/web/src/web-tracer.js
  packages/web/test/requests.test.js
Labels: size/M

#42 fix(README): fake commit to generate a release for epsagon/web
  README.md
Labels: size/XS

#43 Sdk 123 add configuration url patterns to ignore
  packages/web/test/requests.test.js
Labels: size/XS

#44 fix(ignoreURL): add configuration to ignore urls
  packages/web/test/requests.test.js
Labels: size/XS

#45 fix(README): fix README
  README.md
  packages/web/README.md
Labels: size/L

#46 fix(README): add readme to epsagon/web
  packages/web/README.md
Labels: size/L

#47 feat(errors): added global logger handler for scpecific case
  packages/web/src/exporter.js
  packages/web/src/web-tracer.js
Labels: size/S
