Repository epsagon/epsagon-browser, pull requests merged in 2021-09, with the labels that each got.

#49 fix(logs): add logs
  packages/web/src/exporter.js
  packages/web/src/instrumentation/documentLoadInstrumentation.js
  packages/web/src/instrumentation/fetchInstrumentation.js
  packages/web/src/instrumentation/redirectInstrumentation.js
  packages/web/src/instrumentation/xmlHttpInstrumentation.js
  packages/web/src/span-manager.js
  packages/web/src/web-tracer.js
Labels: size/L

#51 Feat/add webpack support/sdk 126
  README.md
  packages/web/package.json
  packages/web/webpack.config.js
Labels: size/M

#53 feat(tests) added tests to run every PR
  .github/workflows/ci.yml
Labels: size/S

#54 Feat/rm react/sdk 157
  .github/workflows/ci.yml
  packages/react/README.md
Labels: size/S

#55 Feat/add commitlint/sdk 155
  .husky/commit-msg
  commitlint.config.js
  package-lock.json
  package.json
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/yarn.lock
Labels: size/XXL

#56 fix(readme): fake commit to initiate npm publish
  README.md
Labels: size/XS

#61 Feat(epsagon-version): add version to resource
  packages/web/src/consts.js
  packages/web/src/exporter.js
  packages/web/src/instrumentation/documentLoadInstrumentation.js
  packages/web/src/resource-manager.js
Labels: size/L

#63 fix(readme): fake commit for semantic release
  README.md
Labels: size/XS
